### ISSUE TITLE
Errors with self-signed certificate

### ISSUE THREAD

**Issue by ewingd** [mkloubert/vscode-http-client#1]
When I attempt to send a request to a server with a self-signed certificate, the only response I receive is "self signed certificate".  How can I configure the client to accept the certificate and continue with the request?

**Comment by mkloubert** [comment]
@ewingd 

According to the following question

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

you can try to start your VS Code with the environment variable `NODE_TLS_REJECT_UNAUTHORIZED = 0`.

But I will implement this in the next version, I will release in some hours.

**Comment by mkloubert** [comment]
@ewingd 

**I released a new version 0.29.0**, which should handle self signed certificates much better, without the upper workarround.

You can use the extension setting `rejectUnauthorized` to control this, but in your case there is nothing to do, the setting is `(false)` by default.

**Comment by ewingd** [comment]
That fixed it, thanks!
